### ISSUE TITLE
pr2 controller debug

### ISSUE THREAD

**Issue by HiroIshida** [HiroIshida/snippets#48]
goal actionに nanが入っていると, nanがはいったjointはそれ以降どんなコマンドを送ってもまともに動かなくなる. 
なおすには, robot restart しないといけない.

次のgoal で上の症状を再現できる.
```
---
header: 
  seq: 5
  stamp: 
    secs: 1701017745
    nsecs: 466095447
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1701017745
    nsecs: 466082096
  id: "/robot_interface_4191474_1701017702570-20-1701017745.466"
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 1701017745
        nsecs: 466016530
      frame_id: ''
    joint_names: 
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    points: 
      - 
        positions: [nan, nan, nan, nan, nan, nan, nan]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: []
        effort: []
        time_from_start: 
          secs: 0
          nsecs:         0
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 6
  stamp: 
    secs: 1701017747
    nsecs: 593964099
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1701017747
    nsecs: 593953371
  id: "/robot_interface_4191474_1701017702570-24-1701017747.594"
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 1701017747
        nsecs: 593899726
      frame_id: ''
    joint_names: 
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    points: 
      - 
        positions: [nan, nan, nan, nan, nan, nan, nan]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: []
        effort: []
        time_from_start: 
          secs: 0
          nsecs:  41364312
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 7
  stamp: 
    secs: 1701017747
    nsecs: 694993972
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1701017747
    nsecs: 694983959
  id: "/robot_interface_4191474_1701017702570-28-1701017747.695"
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 1701017747
        nsecs: 694942951
      frame_id: ''
    joint_names: 
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    points: 
      - 
        positions: [nan, nan, nan, nan, nan, nan, nan]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: []
        effort: []
        time_from_start: 
          secs: 0
          nsecs:  41364312
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 8
  stamp: 
    secs: 1701017747
    nsecs: 772816896
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1701017747
    nsecs: 772797346
  id: "/robot_interface_4191474_1701017702570-32-1701017747.773"
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 1701017747
        nsecs: 772726058
      frame_id: ''
    joint_names: 
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    points: 
      - 
        positions: [nan, nan, nan, nan, nan, nan, nan]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: []
        effort: []
        time_from_start: 
          secs: 0
          nsecs:  41364312
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 9
  stamp: 
    secs: 1701017747
    nsecs: 877955436
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1701017747
    nsecs: 877943992
  id: "/robot_interface_4191474_1701017702570-36-1701017747.878"
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 1701017747
        nsecs: 877900362
      frame_id: ''
    joint_names: 
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    points: 
      - 
        positions: [nan, nan, nan, nan, nan, nan, nan]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: []
        effort: []
        time_from_start: 
          secs: 0
          nsecs:  41364312
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 10
  stamp: 
    secs: 1701017748
    nsecs:   3745555
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1701017748
    nsecs:   3725767
  id: "/robot_interface_4191474_1701017702570-40-1701017748.004"
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 1701017748
        nsecs:   3656148
      frame_id: ''
    joint_names: 
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    points: 
      - 
        positions: [nan, nan, nan, nan, nan, nan, nan]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: []
        effort: []
        time_from_start: 
          secs: 0
          nsecs:  41364312
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 11
  stamp: 
    secs: 1701017748
    nsecs: 111493110
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1701017748
    nsecs: 111482143
  id: "/robot_interface_4191474_1701017702570-44-1701017748.111"
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 1701017748
        nsecs: 111441135
      frame_id: ''
    joint_names: 
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    points: 
      - 
        positions: [nan, nan, nan, nan, nan, nan, nan]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: []
        effort: []
        time_from_start: 
          secs: 0
          nsecs:  41364312
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
header: 
  seq: 12
  stamp: 
    secs: 1701017748
    nsecs: 214805364
  frame_id: ''
goal_id: 
  stamp: 
    secs: 1701017748
    nsecs: 214795351
  id: "/robot_interface_4191474_1701017702570-48-1701017748.215"
goal: 
  trajectory: 
    header: 
      seq: 0
      stamp: 
        secs: 1701017748
        nsecs: 214755773
      frame_id: ''
    joint_names: 
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
    points: 
      - 
        positions: [nan, nan, nan, nan, nan, nan, nan]
        velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        accelerations: []
        effort: []
        time_from_start: 
          secs: 0
          nsecs:  41364312
  path_tolerance: []
  goal_tolerance: []
  goal_time_tolerance: 
    secs: 0
    nsecs:         0
---
```
